@startuml GameDev Notes
skinparam style strictuml
skinparam defaultFontName Courier
skinparam ClassFontStyle bold


class Character {
    'Primary Stats- basis for various Secondary stats'
    -strength: int = 5
    -perception: int = 5
    -endurance: int = 5
    -intelligence: int = 5
    -agility: int = 5
    -luck: int = 5

    level: int = 1
    experiencePoints: int = 0

    'Secondary Stats- calculated using SPECIAL stats'
    -hp: int = <b>10 + END</b>
    -ap: int = <b>10 + AGI/2</b>
    -healingRate: int = 
    <b>END 1-3: 1 HP / 8 hours</b>
    <b>END 4-7: 2 HP / 8 hours</b>
    <b>END 8-10: 3 HP / 8 hours</b>
    -strain: int = 20 {<b>+5 every 5 lvls</b>}
    -karma: int = -10 or 0 or 10 {-100 <= value <= 100}
    -insanity: int = 0 {maximum: <b>5 + INT/2</b>}
    -carryWeight: int = 10 + STR*5

}

note left of Character::strength 
    SPECIAL attributes do not change unless 
    through use of <b>Perks</b> and or <b>Traits</b>.
    They can reach up to a maximum 
    of 15 through use of temp buffs.

    Their default range is {1 <= starting value <= 10}
end note

note right of Character::hp
    All characters have Pain Thresholds
    at 5 HP, 3 HP, and 1 HP
    When that happens, further penalities
    (rolls from GM) will be inflicted on player
end note

note right of Character::karma
    Negative Karma = evil
    Karma around 0 = neutral
    Positive Karma = good
end note

note left of Character::insanity
    When a character is about to get an Insanity Point:
    Roll 1d100
    insanity < 5: if value <= 20, +1 insanity
    insanity >= 5: if value <= 50, +1 insanity

    insanity = maximum, player loses control of
    their character
end note

note left of Character::carryWeight
    Modifiers are applied after calculating base weight.
    currentWeight > carryWeight = Encumbered
    currentWeight >= carryWeight*2 = cant move
end note

@enduml